Change callback_group to MutuallyExclusive
Reentrant callback group sometimes throws an unexpected runtime
exception: 'Executing action client but nothing is ready'. It is caused
because this type of callback group can execute different parts of the
same callback concurrently.